services:
  tiles:
    image: maptiler/tileserver-gl-light:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    command: ["--file", "region.mbtiles"]
